### PR TITLE
Development

### PR DESCRIPTION
**Pull request by LEDominator**
this would add the .gitattributes file for crlf as well as other significant changes

### CODE REVIEW

**Comment by antoniomedrano** [comment]
Re-added #!/usr/bin/python to the files. Ignore undo commit comments.

**Comment by glennon** [comment]
Tested on:

- [ ] Windows
- [ ] Mac
- [ ] Linux
- [ ] Server deployment

**Comment by antoniomedrano** [comment]
platform.system() check fails on Mac when run through Docker.

**Comment by antoniomedrano** [comment]
After reverting routing call to old code, TSP on a network works on a MAC, albeit slowly due to the one-to-one distance calls. Opened new issue #71 to fix this.

**Comment by antoniomedrano** [comment]
Works on Windows, albeit slowly for network.html

**Comment by antoniomedrano** [comment]
@glennon current status of this?

**Comment by glennon** [comment]
yikes. i consider this a deprecated repo (replaced by network-tsp). Just keeping the repo around instead of deleting in case their are useful code snippets in it. As far as this PR, I'd say close without a merge. @antoniomedrano - I added you as an admin to this repo so you can make the call.

**Comment by antoniomedrano** [comment]
@glennon it looks like I'm not an admin, can't merge request.
Reviewing the file changes, there's nothing of consequence in here. Given that it's deprecated anyhow, I say go ahead and merge it.

**Comment by glennon** [comment]
As long as you run and test the code before merging, okay by me. I have not. I did re-add you as admin. Master had extra protection, and you've now been added to that.

**Pull request merged**
